apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
    namespace: db-ns
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
