apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: bloggly-app
    name: bloggly-app
    namespace: app-ns
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bloggly-app
    strategy: {}
    template:
        metadata:
            labels:
                app: bloggly-app
        spec:
            containers:
                - image: yousefmeska/bloggly:latest
                  name: bloggly
                  resources: {}
                  env:
                      - name: POSTGRES_PASS
                        valueFrom:
                            secretKeyRef:
                                key: rootpassword
                                name: mysql-password
                      - name: POSTGRES_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                key: dbname
                                name: app-cm
                      - name: POSTGRES_USER
                        valueFrom:
                            configMapKeyRef:
                                key: dbuser
                                name: app-cm
                      - name: SERVER_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: serverport
                                name: app-cm
                      - name: POSTGRES_HOST
                        valueFrom:
                            configMapKeyRef:
                                key: dbhost
                                name: app-cm
                      - name: POSTGRES_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: dbport
                                name: app-cm
status: {}
