apiVersion: v1
kind: Namespace
metadata:
    labels:
        kubernetes.io/metadata.name: app-ns
    name: app-ns
    resourceVersion: "1913"
spec:
    finalizers:
        - kubernetes
status:
    phase: Active
